name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    env:
      VERSION: "1.0.0"

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r wrkflw_reqs.txt

    - name: Test with unittest
      run: |
        python -m unittest ./app/launcher.py

    - name: Increment version
      id: version-got-from-text
      run: |
        # Vérifier si une mise à jour est disponible
        echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Get App Name
      id: app_name_from_launcher
      run: |
        # Get app name from launcher.py 
        echo "APP_NAME=$(python -c 'from app.launcher import get_app_name; print(get_app_name())')" >> $GITHUB_OUTPUT

    - name: Create Release
      id: create-release
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'merge')
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.version-got-from-text.outputs.VERSION }}
        release_name: Release ${{ steps.version-got-from-text.outputs.VERSION }}
        body: |
          Changes in this Release:
          ${{ github.event.head_commit.message }}
        draft: false
        prerelease: false

    - name: Run pyinstaller for launcher
      run: |
        pyinstaller --name launcher.exe --onefile ./app/launcher.spec
    - uses: actions/upload-artifact@v2
      with:
        name: launcher.exe
        path: ./dist/
        
    - name: Run pyinstaller for app
      run: |
        pyinstaller --name ${{ steps.app_name_from_launcher.outputs.APP_NAME}}.exe --onefile ./app/${{ steps.app_name_from_launcher.outputs.APP_NAME}}.spec
    - uses: actions/upload-artifact@v2
      with:
        name: ${{ steps.app_name_from_launcher.outputs.APP_NAME}}.exe
        path: ./dist/

    - name: ls
      run: ls ./dist/

    - name: Upload asset launcher
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'merge')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./dist/launcher.exe
        asset_name: launcher.exe
        asset_content_type: application/zip

    - name: Upload asset ${{ steps.app_name_from_launcher.outputs.APP_NAME}}
      if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'merge')
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create-release.outputs.upload_url }}
        asset_path: ./dist/${{ steps.app_name_from_launcher.outputs.APP_NAME}}.exe
        asset_name: ${{ steps.app_name_from_launcher.outputs.APP_NAME}}.exe
        asset_content_type: application/zip
